### ISSUE TITLE
Answers() doesnt works at all!

### ISSUE THREAD

**Issue by OnlinePage** [deedy5/duckduckgo_search#115]
**Describe the bug**
What the bug is.
The answers() doesn't works at all for any query😔!

**Debug log**

```python3
answer_query = "france capital"
answers_results = list(ddgs.answers(answer_query))
print(answers_results)
```

Output:
```python3
<Response [200 OK]>
[]
```

**Specify this information**
 - OS- Windows
 - environment- Anaconda python 3.10
 - duckduckgo_search version - latest

**Comment by deedy5** [comment]
`answers` doesn't respond to all requests. 

You can check it in your browser, it's the box to the right of the results. 

For example, the query "France" shows the wikipedia article "France, officially the French Republic, is a ...". 

The query "france capital" shows nothing. 

So that's normal. It may be better to use a normal `text` search.
